### ISSUE TITLE
Issue AddLengths.pl

### ISSUE THREAD

**Issue by rprops** [chrisquince/StrainMetaSim#2]
Hi Chris,

I'm adapting the StrainMetaSim workflow to be applicable to specific MAGs of interest that were generated through alternative binning methods. I'm currently experiencing a bug I believe with the AddLengths.pl script which I'm guessing should merge the contig list file and the gene length file in some way. 
My contigs.txt file looks like this:
```
Ga0224460_1001
Ga0224460_1002
Ga0224460_1003
....
```

My gene length file looks like this:
```
Ga0224460_1001_1        39
Ga0224460_1001_2        123
Ga0224460_1001_3        782
....
```
But when I run:
```
AddLengths.pl MAG8_genes.len < MAG8_contigs.txt >MAG8_contigs.tsv
```

The resulting MAG8_contigs.tsv file looks like this (second column contains all 1's):
```
Ga0224460_1001  1
Ga0224460_1002  1
Ga0224460_1003  1
....
```
When feeding this to Samtools to split the bam files, it of course results in empty splitted bam files.

Do you happen to have any suggestions? If you could define the way these files should be merged I could write my own script to do so as well.

Thank you,

Ruben

**Comment by chrisquince** [comment]
Hi Ruben,

Yes the workflow is confusing as it misses as step where you generate a contig length file. I need to correct it. You actually need to add the contig lengths not the gene lengths to get a bed file format:

contigname 1 endposcontig

tab delimited. Hope that helps?

Best,
Chris

**Comment by rprops** [comment]
Hi Chris,

That did the trick. I will keep you posted when I've finalized my batch script for analyzing specific MAGs using DESMAN. Perhaps it can be of use to distribute within the DESMAN source code.

Thank you!

Ruben

**Comment by rprops** [comment]
Hi Chris,

I've now encountered an issue with `Variant_filter.py` script. When I run it on my frequency file, which looks identical in structure to the test data, `Variant_filter.py`  was running for more than 3 days before being killed (.freq file is 430kb large). It produced no output during that time as well. 
`.scglog` file contained:  
```
2017-12-15 12:03:48,740:INFO:root:Results created at /scratch/rprops/DESMAN/DESMAN_MAG8/Variants/MAG8_scglog.txt
```
I've tried running under different python-versions (2.7/3.0) but the various debugger `*.vout` files did not give me any clues too:  
```
> /home/rprops/DESMAN/desman/Variant_Filter.py(506)main()
    505     import ipdb; ipdb.set_trace()
--> 506     variants    = p.read_csv(variant_file, header=0, index_col=0)
    507

ipdb> ipdb>
KeyboardInterrupt
```
```
--Call--
> /home/rprops/.local/lib/python2.7/site-packages/pandas/io/parsers.py(494)parser_f()
    493
--> 494     def parser_f(filepath_or_buffer,
    495                  sep=sep,

ipdb> ipdb>
KeyboardInterrupt
```
```
> /home/rprops/.local/lib/python2.7/site-packages/pandas/io/parsers.py(567)parser_f()
    566         # Alias sep -> delimiter.
--> 567         if delimiter is None:
    568             delimiter = sep
```

Do you have any ideas on how to best troubleshoot? As far as I can tell the `.freq` file is the sole input for the script.

Thank you,

Ruben

**Comment by rprops** [comment]
Dear Chris,

I have found and resolved my issue. Apparently I had a slightly older version of DESMAN in which the following command line at line 505 was active:
```
import ipdb; ipdb.set_trace()
```
This activated the debugger and thus caused the script to halt. Everything ran fine now and I will close the issue.

Ruben
